# Generated by Django 4.2.13 on 2026-02-19 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FOR_REVIEW', 'For Review'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_code', models.CharField(choices=[('GO', 'Governors Office'), ('IU', 'Governors Office - Information Unit'), ('ITU', 'Governors Office - Information Technology Department'), ('LEDIPO', 'Governors Office - LEDIPO'), ('PNO', 'Provincial Nutrition Office'), ('POPCOM', 'Governors Office - POPCOM'), ('VGO', 'Vice Governors Office'), ('ACCOUNTING', 'Provincial Accounting Office'), ('ADMIN', 'Provincial Administrators Office'), ('PABEO', 'Provincial Agricultural and Biosystems Engineering Office'), ('PASO', 'Provincial Agricultural Services Office'), ('ASSESSOR', 'Provincial Assessor Office'), ('PBMO', 'Provincial Budget and Management Office'), ('PCDO', 'Provincial Cooperative Development Office'), ('PDRRMO', 'Provincial Disaster Risk Reduction and Management Office'), ('PEO-ADMIN', 'Provincial Engineers Office - Administrative'), ('PEO-MAINTENANCE', 'Provincial Engineers Office - Maintenance'), ('PENRO', 'Provincial Environment and Natural Resources Office'), ('PEPO', 'Provincial Equipment Pool Office'), ('PGSO', 'Provincial General Services Office'), ('PHO', 'Provincial Health Office'), ('PHRMDO', 'Provincial Human Resource Management Development Office'), ('PIASO', 'Provincial Internal Audit Services Office'), ('PLO', 'Provincial Legal Office'), ('PPDAO', 'Provincial Persons with Disability Affairs Office'), ('PPDO', 'Provincial Planning and Development Office'), ('PPESO', 'Provincial Public Employment Service Office'), ('PSWDO', 'Provincial Social Welfare and Development Office'), ('TOURISM', 'Provincial Tourism Office'), ('TREASURER', 'Provincial Treasurers Office'), ('PVO', 'Provincial Veterinary Office'), ('PYDO', 'Provincial Youth Development Office'), ('SP-LEGISLATIVE', 'Sangguniang Panlalawigan - Legislative Services'), ('SP-SUPPORT', 'Sangguniang Panlalawigan - Support Services')], max_length=50, unique=True)),
                ('office_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['office_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HEAD', 'Office Head'), ('STAFF', 'Staff'), ('GOVERNOR', 'Governor'), ('EXECUTIVE', 'Executive'), ('ADMIN', 'Administrator')], default='STAFF', max_length=20)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FOR_REVIEW', 'For Review'), ('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='tracking.document')),
                ('from_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routings_from', to='tracking.office')),
                ('to_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routings_to', to='tracking.office')),
            ],
        ),
    ]
