# Generated by Django 4.2.13 on 2026-03-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='remarks',
            field=models.TextField(blank=True, help_text='Feedback or reason from the receiver', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Comment from the sender/uploader'),
        ),
    ]
