# Generated by Django 4.2.13 on 2026-02-16 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0002_alter_department_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_ocr', models.TextField(blank=True, null=True)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_final', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='tracking.document')),
            ],
            options={
                'ordering': ['-routed_at'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=150, unique=True)),
                ('parent_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_offices', to='tracking.office')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='documentrouting',
            name='from_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_routings', to='tracking.office'),
        ),
        migrations.AddField(
            model_name='documentrouting',
            name='routed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrouting',
            name='to_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_routings', to='tracking.office'),
        ),
        migrations.AddField(
            model_name='document',
            name='origin_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originated_documents', to='tracking.office'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.office'),
        ),
    ]
