# Generated by Django 4.2.13 on 2026-02-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_office_office_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('HEAD', 'Office Head'), ('STAFF', 'Staff'), ('GOVERNOR', 'Governor'), ('EXECUTIVE', 'Executive'), ('ADMIN', 'Administrator')], default='STAFF', max_length=20),
        ),
    ]
