# Generated by Django 6.0.2 on 2026-03-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FOR_REVIEW', 'For Review'), ('RECEIVED', 'Received'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='routing',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FOR_REVIEW', 'For Review'), ('RECEIVED', 'Received'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
